checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*

build:
  nodes:
    php73:
      environment:
        php:
          version: 7.3
      tests:
        override:
          - php-scrutinizer-run
          -
            command: vendor/bin/phpunit --coverage-clover=coverage73
            coverage:
              file: coverage73
              format: php-clover
    php80:
      environment:
        php:
          version: "8.0.0"
      tests:
        override:
          - php-scrutinizer-run
          -
            command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage80
            coverage:
              file: coverage80
              format: php-clover
