checks:
  php: true

filter:
  excluded_paths:
    - tests/*

build:
  environment:
    php:
      version: 7.0
  tests:
    override:
      -
        command: vendor/bin/phpunit --coverage-clover=coverage.clover
        coverage:
          file: coverage.clover
          format: php-clover
